# Generated by Django 4.1.5 on 2023-01-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sdntool", "0002_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceDataStore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_path", models.CharField(max_length=200)),
            ],
            options={"db_table": "evidence_data_store",},
        ),
        migrations.CreateModel(
            name="EvidenceData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("element_name", models.CharField(max_length=200)),
                ("evidence_type", models.CharField(max_length=200)),
                (
                    "evidence_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sdntool.evidencedatastore",
                    ),
                ),
            ],
            options={"db_table": "evidence_data",},
        ),
    ]
