# Generated by Django 4.1.5 on 2023-01-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sdntool", "0003_evidencedatastore_evidencedata"),
    ]

    operations = [
        migrations.DeleteModel(name="EvidenceData",),
        migrations.DeleteModel(name="EvidenceDataStore",),
    ]
