# Generated by Django 4.1.5 on 2023-01-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvidenceDataStore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("network_name", models.CharField(max_length=255)),
                ("is_log", models.BooleanField(default=False)),
                ("evidence_type", models.CharField(max_length=100)),
                ("elements_involved", models.JSONField()),
                (
                    "evidence_date",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policymanagement.evidencedatastore",
                    ),
                ),
            ],
        ),
    ]
