# Generated by Django 4.1.5 on 2023-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policymanagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evidencedata",
            old_name="evidence_date",
            new_name="evidence_data",
        ),
        migrations.AddField(
            model_name="evidencedata",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="evidencedata",
            name="elements_involved",
            field=models.TextField(),
        ),
    ]
